variables:
  appFolder: 'personal-website'
  registry: 'pelter-gmail-dockerhub'
  registryUser: 'jpelter'
  imageName: 'pelter-react-frontend'

pr: none

trigger:
  batch: true
  branches:
    include:
    - feature/*
    - main
  paths:
    include:
    - personal-website

jobs:
- job: Build
  displayName: Docker build and push
  pool:
    name: Azure Pipelines
  steps:
  - task: Docker@2
    displayName: Build
    inputs:
      command: build
      repository: $(registryUser)/$(imageName)
      dockerfile: $(appFolder)/Dockerfile
      tags: |
        $(Build.BuildId)
        
  - task: Docker@2
    displayName: Push
    inputs:
      command: push
      repository: $(registryUser)/$(imageName)
      containerRegistry: $(registry)
      tags: |
        $(Build.BuildId)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(appFolder)/charts
      artifactName: 'drop'